-- FlowPromos: migração de Drizzle/MySQL para Supabase/PostgreSQL
-- A tabela public.profiles representa a antiga users e usa o UUID do Supabase Auth.
-- legacy_id/open_id preservam referências para uma importação gradual dos dados atuais.

create extension if not exists pgcrypto;

create type public.user_role as enum ('user', 'admin');
create type public.user_status as enum ('active', 'suspended', 'pending');
create type public.plan_code as enum ('none', 'essencial', 'pro', 'expert', 'anual');
create type public.plan_status as enum ('trial', 'active', 'cancelled', 'expired');
create type public.integration_provider as enum ('whatsapp', 'telegram', 'amazon', 'shopee', 'mercadolivre');
create type public.integration_status as enum ('connected', 'disconnected', 'error');
create type public.billing_cycle as enum ('monthly', 'annual');
create type public.subscription_status as enum ('active', 'pending', 'past_due', 'cancelled');
create type public.subscription_change_status as enum ('completed', 'failed');
create type public.whatsapp_status as enum ('disconnected', 'connecting', 'connected');
create type public.group_platform as enum ('whatsapp', 'telegram');
create type public.store_code as enum ('all', 'shopee', 'amazon', 'magalu', 'mercadolivre', 'aliexpress');
create type public.offer_status as enum ('detected', 'scheduled', 'sent', 'ignored');
create type public.dispatch_status as enum ('pending', 'processing', 'sent', 'failed');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  legacy_id bigint unique,
  open_id text unique,
  name text,
  email text,
  password_hash text,
  login_method text not null default 'supabase_auth',
  role public.user_role not null default 'user',
  status public.user_status not null default 'active',
  plan public.plan_code not null default 'none',
  plan_status public.plan_status not null default 'trial',
  expires_at timestamptz,
  whatsapp_number text,
  shopee_tag text,
  amazon_tag text,
  magalu_tag text,
  aliexpress_tag text,
  mercado_livre_tag text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz
);

create table public.plans (
  id text primary key,
  name text not null,
  description text,
  price_monthly integer not null,
  price_annual integer not null,
  offers_limit_per_day integer not null,
  groups_limit integer not null,
  channels_limit integer not null,
  quality_score_max integer not null,
  stores_limit integer not null,
  is_popular boolean not null default false,
  stripe_price_id_monthly text,
  stripe_price_id_annual text
);

create table public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  legacy_id bigint unique,
  plan_id text not null references public.plans(id),
  billing_cycle public.billing_cycle not null default 'annual',
  status public.subscription_status not null default 'pending',
  amount integer not null,
  payment_method text default 'stripe_card',
  stripe_subscription_id text unique,
  stripe_customer_id text,
  start_date timestamptz not null default now(),
  end_date timestamptz not null,
  created_at timestamptz not null default now()
);

create table public.subscription_changes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  subscription_id bigint not null references public.subscriptions(id) on delete cascade,
  from_cycle public.billing_cycle,
  to_cycle public.billing_cycle not null,
  amount integer not null,
  status public.subscription_change_status not null default 'completed',
  source text not null default 'stripe',
  stripe_subscription_id text,
  created_at timestamptz not null default now()
);

create table public.integration_connections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  provider public.integration_provider not null,
  encrypted_credentials text not null,
  status public.integration_status not null default 'connected',
  last_error text,
  last_tested_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider)
);

create table public.whatsapp_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_name text not null,
  status public.whatsapp_status not null default 'disconnected',
  phone text,
  qr_code_url text,
  last_seen timestamptz,
  updated_at timestamptz not null default now()
);

create table public.affiliate_groups (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  legacy_id bigint unique,
  platform public.group_platform not null default 'whatsapp',
  group_id text not null,
  name text not null,
  segment text default 'Geral',
  is_active boolean not null default true,
  members_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.segments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  legacy_id bigint unique,
  name text not null,
  store public.store_code not null default 'all',
  keywords text not null,
  min_discount_percentage integer not null default 15,
  min_quality_score integer not null default 60,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.offers (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  legacy_id bigint unique,
  store text not null,
  title text not null,
  category text,
  original_price integer not null,
  promo_price integer not null,
  discount_percent integer not null,
  coupon text,
  free_shipping boolean not null default false,
  verified_seller boolean not null default true,
  quality_score integer not null default 85,
  original_url text not null,
  affiliate_url text not null,
  image_url text,
  status public.offer_status not null default 'detected',
  created_at timestamptz not null default now()
);

create table public.dispatches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  legacy_id bigint unique,
  offer_id bigint references public.offers(id) on delete set null,
  group_id bigint references public.affiliate_groups(id) on delete set null,
  message_content text not null,
  status public.dispatch_status not null default 'pending',
  scheduled_for timestamptz not null default now(),
  sent_at timestamptz,
  error_message text,
  created_at timestamptz not null default now()
);

create index subscriptions_user_status_idx on public.subscriptions(user_id, status);
create index subscription_changes_user_created_idx on public.subscription_changes(user_id, created_at desc);
create index integration_connections_user_idx on public.integration_connections(user_id);
create index affiliate_groups_user_idx on public.affiliate_groups(user_id);
create index segments_user_idx on public.segments(user_id);
create index offers_user_idx on public.offers(user_id);
create index dispatches_user_status_idx on public.dispatches(user_id, status);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;
create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger integration_connections_updated_at before update on public.integration_connections for each row execute function public.set_updated_at();
create trigger whatsapp_sessions_updated_at before update on public.whatsapp_sessions for each row execute function public.set_updated_at();

-- Cria o perfil automaticamente quando um usuário nasce no Supabase Auth.
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, name, role)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'name', new.email), 'user')
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

-- RLS: o usuário acessa somente os próprios registros; admins podem acessar tudo via policies específicas.
alter table public.profiles enable row level security;
alter table public.plans enable row level security;
alter table public.subscriptions enable row level security;
alter table public.subscription_changes enable row level security;
alter table public.integration_connections enable row level security;
alter table public.whatsapp_sessions enable row level security;
alter table public.affiliate_groups enable row level security;
alter table public.segments enable row level security;
alter table public.offers enable row level security;
alter table public.dispatches enable row level security;

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

create policy profiles_self_or_admin on public.profiles for select using (id = auth.uid() or public.is_admin());
create policy profiles_self_update on public.profiles for update using (id = auth.uid() or public.is_admin()) with check (id = auth.uid() or public.is_admin());
create policy plans_authenticated_read on public.plans for select to authenticated using (true);

create policy subscriptions_owner_or_admin on public.subscriptions for all using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy subscription_changes_owner_or_admin on public.subscription_changes for select using (user_id = auth.uid() or public.is_admin());
create policy integration_owner_or_admin on public.integration_connections for all using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy whatsapp_owner_or_admin on public.whatsapp_sessions for all using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy groups_owner_or_admin on public.affiliate_groups for all using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy segments_owner_or_admin on public.segments for all using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy offers_owner_or_admin on public.offers for all using (user_id = auth.uid() or user_id is null or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());
create policy dispatches_owner_or_admin on public.dispatches for all using (user_id = auth.uid() or public.is_admin()) with check (user_id = auth.uid() or public.is_admin());

comment on table public.profiles is 'Migrated from Drizzle users; id is Supabase Auth UUID and legacy_id maps the old integer id.';
comment on table public.subscription_changes is 'History of monthly/annual subscription changes, including Stripe failures.';
