create table if not exists public.message_templates (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 100),
  message text not null check (char_length(message) between 1 and 4000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists message_templates_user_created_idx
  on public.message_templates(user_id, created_at desc);

alter table public.message_templates enable row level security;

create policy message_templates_owner_or_admin
  on public.message_templates for all
  using (user_id = auth.uid() or public.is_admin())
  with check (user_id = auth.uid() or public.is_admin());

create trigger message_templates_updated_at
  before update on public.message_templates
  for each row execute function public.set_updated_at();
